### ISSUE TITLE
index.php accessible structure

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#10]
### Is your feature request related to a problem? Please describe.
Best practice for accessible templates is consequent usage of landmarks (sections).

### Describe the solution you'd like
Replace divs by sections where possible

### Additional context
This has been already started by Hans Kuipers - must be integrated into the project

**Comment by chmst** [comment]
As JAT requested that modules must be tagged as section, this mus be madt in installation data for the login and main menu - and in sample data for all modules. 

Open question: Why is it necessary only in frontend and never was required for the backend modules?

**Comment by brianteeman** [comment]
because like all generic advice its not correct or perhaps just not complete

1. It is often the module position that **could** be a section not a module especially if there is more than one module in the position
2. the landmark may or may not be a section depending on the content of the module. there are lots of different landmarks
3. modules can already have appropriate landmarks set in their advanced options
4. making the module position a landmarked area in the template is probably going to make things worse and not better as you will end up with a template designer choosing the landmark. When the site builder puts a menu module in a position where the designer used the landmark **aside** it is worse not better.
5. this is one of the limitations of a flexible system like joomla.

![image](https://user-images.githubusercontent.com/1296369/91810767-5fe55980-ec26-11ea-807b-fcdda167d4c4.png)

**Comment by chmst** [comment]
Understood. I'll close this issue.

**Comment by brianteeman** [comment]
Thanks - I assume the JAT have been informed that their request is closed?

**Comment by chmst** [comment]
@hans2103 and me will discuss this in JAT.

**Comment by brianteeman** [comment]
thanks
