### ISSUE TITLE
Template Param: Selection of a Google Font

### ISSUE THREAD

**Issue by drmenzelit** [joomla/cassiopeia#15]

**Comment by richard67** [comment]
I've prepared a target branch for other works related to Google fonts, mainly for issue #14 : https://github.com/joomla/cassiopeia/tree/4.0-dev-google-fonts-enhancements.

Do you think it makes sense to handle the implementation to solve this issue here with the same branch?

Or should we keep it separate? if so, let me know and I create a new target branch for that.

**Comment by chmst** [comment]
Closed as we have a PR
