### ISSUE TITLE
Double underline in navbar

### ISSUE THREAD

**Issue by Quy** [joomla/cassiopeia#162]
### Steps to reproduce the issue
Is this the desired effect?

### Actual result

![underline](https://user-images.githubusercontent.com/368084/94832935-643a9900-03c3-11eb-8f36-4f3b30c87533.png)

**Comment by drmenzelit** [comment]
No, that is not correct...
`not(.container-header) .mod-menu.nav li.active > a, :not(.container-header) .mod-menu.nav li a:hover {
    text-decoration: underline;
}`
is not doing the trick... We need to check again

**Comment by richard67** [comment]
Has been solved with #163 .

**Comment by richard67** [comment]
It seems it either has not been fully solved with PR #163 , or it came back with the later PR #175 .

How to reproduce:

1. On desktop, start with big browser window.
2. Select menu item "About" in the menu at the top so that it is the active menu item.
Result: It gets a blue underline.
3. Slowly reduce browser window width and watch the "About" menu item.
Result: At a certain point a second, white underline appears.

![2020-10-21_02](https://user-images.githubusercontent.com/7413183/96695969-8c963180-138a-11eb-8e31-a4ee86e4ffc3.png)

When reducing width further, the blue underline disappears so only the white remains.

@drmenzelit Could you have a look on that? It seems some media breakpoints need to be made consistent here and there. Thanks in advance.

**Comment by drmenzelit** [comment]
I will check it

**Comment by richard67** [comment]
Finally solved with PR #193 .
