### ISSUE TITLE
Wrong media query for metismenu

### ISSUE THREAD

**Issue by drmenzelit** [joomla/cassiopeia#86]
### Steps to reproduce the issue
Check the navbar at different display sizes. The hamburger icon appears at 991px width, but the menu is still horizontal

### Expected result
The menu changes to vertical, when hamburger menu appears.

### Actual result
The menu is still horizontal.

**Comment by richard67** [comment]
~~That's very similar to what I had discovered here: https://github.com/joomla/joomla-cms/pull/30131 .~~

~~The problem is that we have 2 such buttons, the hamburger and the gears, which have same class and so appear at the same time when reducing the display width from large to smaller, but the stuff shown or hidden by these buttons disappears at different points of time.~~

~~But because those 2 buttons are handled in the same way, it will happen that when we fix the hamburger button we have then a problem with the gears button.~~

Silly me. That was the backend.

**Comment by drmenzelit** [comment]
We need to change navbar-expand-lg to navbar-expand-md in the index.php or change the media-breakpoint-up(md) to media-breakpoint-up(lg) for the menu stuff in _header.scss

**Comment by richard67** [comment]
And which of these 2 ways is the better way?

**Comment by drmenzelit** [comment]
I'm not sure...

**Comment by richard67** [comment]
>We need to change navbar-expand-lg to navbar-expand-md in the index.php or change the media-breakpoint-up(md) to media-breakpoint-up(lg) for the menu stuff in _header.scss
>
>> And which of these 2 ways is the better way?
>
> I'm not sure...

Who could we ask? Maybe @ciar4n ?

**Comment by richard67** [comment]
Solved with PR #153 .
